Bump the typing-stubs group with ~5~ 3 updates
Bumps the typing-stubs group with ~5~ 3 updates:

| Package | From | To |
| --- | --- | --- |
| [boto3-stubs](https://github.com/youtype/mypy_boto3_builder) | `1.33.11` | `1.34.2` |
| [botocore-stubs](https://github.com/youtype/botocore-stubs) | `1.33.11` | `1.34.2` |
| [mypy-boto3-ses](https://github.com/youtype/mypy_boto3_builder) | `1.33.0` | `1.34.0` |

Updates `boto3-stubs` from 1.33.11 to 1.34.2
- [Release notes](https://github.com/youtype/mypy_boto3_builder/releases)
- [Commits](https://github.com/youtype/mypy_boto3_builder/commits)

Updates `botocore-stubs` from 1.33.11 to 1.34.2
- [Release notes](https://github.com/youtype/botocore-stubs/releases)
- [Commits](https://github.com/youtype/botocore-stubs/commits)

Updates `mypy-boto3-ses` from 1.33.0 to 1.34.0
- [Release notes](https://github.com/youtype/mypy_boto3_builder/releases)
- [Commits](https://github.com/youtype/mypy_boto3_builder/commits)

The update to `django-stubs` 4.2.7 was removed because mypy doesn't like
it. It gives warnings like:

```
emails/models.py:772: error: "User" has no attribute "profile"  [attr-defined]
privaterelay/tests/utils_tests.py:524: error: "Group" has no attribute "user_set"  [attr-defined]
api/tests/views_tests.py:49: error: "User" has no attribute "profile"  [attr-defined]
```

The update to `djangorestframework-stubs` 3.14.5 was removed because it
requires `django-stubs` 4.2.7.

---
updated-dependencies:
- dependency-name: boto3-stubs
  dependency-type: direct:production
  update-type: version-update:semver-minor
  dependency-group: typing-stubs
- dependency-name: botocore-stubs
  dependency-type: direct:production
  update-type: version-update:semver-minor
  dependency-group: typing-stubs
- dependency-name: mypy-boto3-ses
  dependency-type: direct:production
  update-type: version-update:semver-minor
  dependency-group: typing-stubs
...

Signed-off-by: dependabot[bot] <support@github.com>